### PR TITLE
close #31 | create an icon

### LINKED ISSUE #31: Create an icon for Rapido
**Rapido** is looking for an icon, any idea is welcome.

### PR DESCRIPTION
**Pull request by riccardoscalco**
I added an icon based on a typeface, the idea is to express speed and have a bit of contrast with the other page content. Please, let me know what you think.

### CODE REVIEW

**Comment by rpadovani** [comment]
I like it, but let's hear also from @alessandrobessi @lucagrementieri

**Comment by lucagrementieri** [comment]
Nice icon!

**Comment by alessandrobessi** [comment]
I like it!

**Comment by riccardoscalco** [comment]
Cool, thanks guys :)

**Pull request merged**
